name: Gradle Enterprise Trial

on:
  pull_request: {}
  push: { branches: [ master ] }

env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}


jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { XDG_RUNTIME_DIR: "" }
          - { XDG_RUNTIME_DIR: "/tmp/docker-testcontainers/" }
    env:
      XDG_RUNTIME_DIR: ${{ matrix.XDG_RUNTIME_DIR }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.1
        with:
          java-version: '8.0.302'
          distribution: temurin
      - name: Build with Gradle
        run: ./gradlew --no-daemon clean testcontainers:check -Dscan.tag.exp4
